version: "3.8"
volumes:
  postgres_volume:

services:
  pg-edication-bot-db:
    image: postgres:14-alpine3.15
    container_name: "pg-edication-bot-db"
    environment:
      - POSTGRES_DB=edication-bot
      - POSTGRES_USER=edication-bot-user
      - POSTGRES_PASSWORD=edication-bot-password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 54322:5432
